// <auto-generated />
using System;
using Boss.DDD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boss.DDD.Migrations
{
    [DbContext(typeof(DealerEFCoreContext))]
    partial class DealerEFCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Boss.DDD.POCOModels.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactTel");

                    b.Property<Guid>("DealersId");

                    b.Property<int>("IsDefaultContact");

                    b.Property<string>("jiedao");

                    b.Property<string>("qu");

                    b.Property<string>("sheng");

                    b.Property<string>("shi");

                    b.HasKey("Id");

                    b.HasIndex("DealersId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Boss.DDD.POCOModels.Dealers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardType");

                    b.Property<string>("Code");

                    b.Property<Guid?>("DealerTreeId");

                    b.Property<decimal>("JangJingMoney");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int>("SubCount");

                    b.Property<string>("Tel");

                    b.Property<decimal>("TotalEleMoney");

                    b.Property<decimal>("TotalPV");

                    b.HasKey("Id");

                    b.HasIndex("DealerTreeId");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Boss.DDD.POCOModels.DealerTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DealerId");

                    b.Property<int>("Layer");

                    b.Property<Guid?>("ParentDealerId");

                    b.HasKey("Id");

                    b.ToTable("DealerTree");
                });

            modelBuilder.Entity("Boss.DDD.POCOModels.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<Guid>("DealerId");

                    b.Property<string>("PassWord");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Boss.DDD.POCOModels.Contact", b =>
                {
                    b.HasOne("Boss.DDD.POCOModels.Dealers")
                        .WithMany("Contacts")
                        .HasForeignKey("DealersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boss.DDD.POCOModels.Dealers", b =>
                {
                    b.HasOne("Boss.DDD.POCOModels.DealerTree", "DealerTree")
                        .WithMany()
                        .HasForeignKey("DealerTreeId");
                });
#pragma warning restore 612, 618
        }
    }
}
